language: go
sudo: false
go:
  - 1.4
  - 1.5.1

# Gracefully handle developer forks
install: |
    go get golang.org/x/tools/cmd/vet
    go get github.com/golang/lint/golint
    MANTLE_DIR="${GOPATH}/src/github.com/coreos/mantle"
    if [[ "${TRAVIS_BUILD_DIR}" != "${MANTLE_DIR}" ]]; then
        mkdir -p "${MANTLE_DIR%/*}"
        mv "${TRAVIS_BUILD_DIR}" "${MANTLE_DIR}"
        export TRAVIS_BUILD_DIR="${MANTLE_DIR}"
        cd "${TRAVIS_BUILD_DIR}"
    fi

script:
  - go fmt github.com/coreos/mantle/...
  - go vet github.com/coreos/mantle/...
  - golint github.com/coreos/mantle/...

