#!/usr/bin/env bash

set -e

cd $(dirname $0)

source ./env

if [[ $# -eq 0 ]]; then
	set -- cmd/*
fi

version=$(git describe --dirty)
version="${version#v}"
version="${version/-/+}"
ldflags="-X ${REPO_PATH}/version.Version=${version}"

host_build() {
	echo "Building $1"

	if [[ "${GOHOSTARCH}" == "${GOARCH}" ]]; then
		install_dir="bin"
	else
		install_dir="bin/${GOARCH}"
	fi
	mkdir -p "${install_dir}"
	go build -ldflags "${ldflags}" -o "${install_dir}/$1" "${REPO_PATH}/cmd/$1"
}

cross_build() {
	[[ -z "${NO_CROSS}" ]] || return 0
	local a
	for a in amd64 arm64; do
		echo "Building $a/$1"
		mkdir -p "bin/$a"
		CGO_ENABLED=0 GOARCH=$a \
			go build -ldflags "${ldflags}" \
			-o "bin/$a/$1" "${REPO_PATH}/cmd/$1"
	done
}

for cmd in "$@"; do
	cmd=$(basename "${cmd}")
	if [[ "${cmd}" == kolet ]]; then
		cross_build kolet
	else
		host_build "${cmd}"
	fi
done
