# Image for compiling mantle.

FROM arm64v8/ubuntu:17.10

ARG GO_VERSION=1.10

RUN apt-get update && apt-get install -y \
	apt-utils \
	gcc \
	git \
	wget \
	&& rm -rf /var/lib/apt/lists/*

RUN wget --no-verbose https://storage.googleapis.com/golang/go${GO_VERSION}.linux-arm64.tar.gz && \
	tar -C /usr/local -xf go${GO_VERSION}.linux-arm64.tar.gz && \
	rm go${GO_VERSION}.linux-arm64.tar.gz

ENV PATH /usr/local/go/bin:${PATH}

CMD /bin/bash
